---
- name: Make sure there is rsyslog
  package:
    name: rsyslog
    state: present
- name: Start syslog service
  service:
    name: rsyslog
    state: started

- name: Config rsyslog
  template: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - { src: 'files/rsyslog.j2', dest: '/etc/rsyslog.conf' }
  notify: Restart syslog
