---
- name: Stop grafana
  docker_container:
    name: grafana
    state: absent

- name: Build custom grafana image
  docker_image:
    path: /tmp/grafana/
    name: "{{ grafana_image_name }}"
    state: present
    force: yes
    
